namespace test_crud.core.DTOs
{
    public class UserDto
    {
        /// <summary>
        /// Autogenerated id for user entity
        /// </summary>
        public int Id { get; set; }
        public string TxtUser { get; set; }
        public string TxtName { get; set; }
        public string TxtLastName { get; set; }
        public string IdentityCardNum { get; set; }
        public int? RoleCode { get; set; }
        public int? IsActive { get; set; }
    }
}
